### ISSUE TITLE
Make population class

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#10]
- `std::vector<Individual>`をメンバ変数として持つような集団クラスを作る
- `int`をひとつとるコンストラクタを書いて、実装部でその数だけ個体を`push_back()`していく。
- 各個体のID(とできれば両親のIDも)を表示するメンバ関数を作って、`main()`で使う。

**Comment by heavywatal** [comment]
新しいクラスを作るのも慣れたもんですね。だいたい良いのですが、いくつか改善すべき点があります:

- `add_population_number` という引数の名前があまり良くない。addが動詞なので関数ぽいのと、population numberってあまり聞いたことがなくて意味が分からないのと。。。
- `individual_vector` という名前に違和感。こっちはまあ好みの問題ですが、`vector`のような型の情報を名前に持たせるハンガリアン記法的なのはC++ではあまり良い習慣とされていません。
- とりあえず父母を持つ子供じゃなくて、デフォルトコンストラクタで作った個体をバンバン`push_back()`してください。それができたら、初期化子で初期化してみる場合も試してみて、なぜそれじゃダメか、を実感しておくとなお良いです。
- `get_individual_ids()` の名前に偽りあり。IDじゃなくて個体クラスを丸ごと返しちゃってますね。`std::cout`に流すとこまでやるメンバ関数をPopulationに作って、`main()`ではそれを呼び出すだけにしてください。

**Comment by heavywatal** [comment]
あ、あとそのマシンはまだGithubアカウントがちゃんと設定されてないみたいです。
https://github.com/teTUNAakita/cpp_practice/commits/master

**Comment by teTUNAakita** [comment]
> デフォルトコンストラクタで作った個体をバンバンpush_back()してください。それができたら、初期化子で初期化してみる場合も試して

クラスPopulationの内部でやってみました。初期化子で個体数を初期化してバンバンpush_back()していますが、この方法のデメリットをまだ感じ取れないです。。

**Comment by heavywatal** [comment]
すいませんちょっと曖昧でしたが、ダメなのは`push_back()`じゃなくて、初期化子で`std::vector<Individual>`に個体を詰めてしまうことのほうです。`std::vector`のコンストラクタを調べて書き直し、出力結果を見てみて下さい。ちなみに同じ理由で`assign()`メンバ関数を使う方法もダメです。

あと些細なことですが`push_back()`前に名前付き変数を作らずに`push_back(Individual());`で済ませちゃったほうが見た目もパフォーマンスも良いです。

**Comment by teTUNAakita** [comment]
```
class Population
{
private:
    const int pop_size;
    std::vector<Individual> children;
public:
    Population(const int child_number) : pop_size(child_number), children(child_number) {
        /*
        for (int i = 0; i < pop_size; i++){
            children.push_back(Individual());
        }
         */
    };
    void print_child_id() {
        for (int i = 0; i < pop_size; i++){
            std::cout << "child_id=" << (children[i]).get_id() << std::end;

        }
    }
};
int main()
{
    Population pop(5);
    pop.print_child_id();
}

```
`push_back()`を用いずに、初期化子で`std::vector<Individual>`を初期化すると、正しく？idが出力されてしまうように見えるのですが、これはなぜですか？

**Comment by heavywatal** [comment]
ありゃ、妙ですね。仕様では、最初に生成されたオブジェクトがコピーされるので、同じIDの個体たちができてしまうはずなんですが。C++14で変更でもあったかな。。。すいませんちょっと調べてみます。
http://www.cplusplus.com/reference/vector/vector/vector/

**Comment by heavywatal** [comment]
すいません、どうやら僕の知識不足で、これはC++11からの新仕様らしいです。
http://en.cppreference.com/w/cpp/container/vector/vector
`children(n, Individual())`のようにサイズと値を両方渡すとコピー、`children(n)`のようにサイズだけ渡すと毎回デフォルトで生成、となるようです。

`pop_size`というメンバ変数は冗長ですし、実際の`children.size()`と常に同期していることを確約するのは難しい(し、まして`const`では不可能な)ので消した方がいいです。その修正コミットでcloseしてください。

**Comment by heavywatal** [comment]
cplusplus.com に修正の要望を送りました。
