### ISSUE TITLE
Non overlapping generations

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#11]
8個体でスタート。4ペアそれぞれが2個体の子供を作って`std::vector<Individual>`メンバ変数を子供世代に置き換える、というメンバ関数を作って3周くらい回してみましょう。乱数はとりあえず無しで。

**Comment by teTUNAakita** [comment]
`std::vector<Individual>children[i] = Individual(i,i+1)`といった代入が上手くいかないです。エラーメッセージを解読しきれていないかもです。
```
main.cpp:37:25: error: object of type 'Individual' cannot be assigned because
      its copy assignment operator is implicitly deleted
            children[i] = Individual(i,i+1);
                        ^
main.cpp:14:15: note: copy assignment operator of 'Individual' is implicitly
      deleted because field 'id' is of const-qualified type 'const int'
    const int id;
```

**Comment by heavywatal** [comment]
`Individual`クラスにコピー代入演算子が定義されてない、というのがエラーの至近要因で、それを定義すれば解消できますが、根本的におかしいのでそれについてはとりあえず置いておきましょう。
- `main()`で`Population`オブジェクトを何回も生成してますが、1回でいいです。1回作った集団について、3世代回すのが今回の主旨です。
- `Population`クラスのコンストラクタは、デフォルトコンストラクタで8個体詰めて第一世代を作ったらそれで終わりです。これは前のコミットで完成してます。
- 世代を回すメンバ関数を別に作りましょう。その関数の中で、次世代用の空の`std::vector<Individual>`を一時変数として作り、そこに子供たちを`push_back()`して、`Population`クラスのメンバ変数と`swap()`するのがベストプラクティスです。そうすればたぶんコピー代入演算子を定義しなくてもいけるはずです。
- (こうしてみると、メンバ変数の名前が`children`なのは違和感ありますよね？)

**Comment by teTUNAakita** [comment]
まずは、１倍体ver.をつくってみました。８個体スタートで、各個体が１個体生むというモデルで、３世代回しました。

**Comment by heavywatal** [comment]
> 世代を回すメンバ関数を別に作りましょう。その関数の中で、次世代用の空のstd::vector<Individual>を一時変数として作り、

と書いてあるとおり、それで良いです。`swap()`もちゃんとできてますね。素晴らしい。元の親世代のvectorだったものは一時変数のほうにすげ替えられて、関数スコープを出る時に破棄されます。Rとかと違ってオブジェクトの寿命が分かりやすくていいですよね。

ひとつ改善するとしたら`print_individual_id()`と`update()`の引数で、無いほうがいいです。`i < tmp_adults.size()`などとしてvectorのサイズを基準にすればどんな大きさでも対応できますよね。

そのほか、些末な問題ですが、名前の違和感がいくつか。
- `tmp_children`は関数のスコープ内で生成されて破棄される一時変数なので文字通りtmpなんですが、`tmp_adults`はずっと存在してるメンバ変数なのでtmpはおかしいです。
- generation time って1世代あたりの時間を意味する用語じゃなかったでしたっけ？

このへんをチャチャっと修正してcloseしちゃってください。
