### ISSUE TITLE
Print genealogy information in some readable format

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#12]
家系図の情報をどうプリントしたら次の解析に使いやすいでしょうか？最終的に何をしたいのか僕ちょっと把握しきれてないのですが、描画したりしますよね？例えばedge-listという形式はただのタブ区切りテキストなので作りやすいですし、RのigraphやPythonのNetworkXなど一般的なグラフ関連ライブラリで利用可能だと思います。
```
from to
0 1
0 2
3 4
3 5
```

**Comment by teTUNAakita** [comment]
色々ありがとう。最終的には2017/1/23にある発表に合うように、２倍体の家系図を前向きに作成＆後ろ向きに追うことを再現・図示したいです。親が残す子の数は、指定した分布に従うと仮定。できれば、齢構成ありでもやりたいです。

**Comment by heavywatal** [comment]
「後ろ向きに追う」が具体的にどういうことするのか分かりませんが、だいたい了解です。とりあえず出力フォーマットを整えましょう。二倍体にして、1個体につき2行ずつ書き出してください。

**Comment by teTUNAakita** [comment]
前向きの意味は、集団全部の全世代について親子情報を作るということ。後向きで追うの意味は、作成した集団全体の家系図について、あるタイミングの集団もしくはサンプルから過去を遡っていき、MRCAのようなところまで家系図を作る、という意味でした。何れにせよ、前向きの家系シミュレーションで、情報を失わないようにすればできると想定しています。

**Comment by heavywatal** [comment]
了解です！

**Comment by teTUNAakita** [comment]
> とりあえず出力フォーマットを整えましょう。二倍体にして、1個体につき2行ずつ書き出してください。

具体的にどのようなイメージ？？
* いろいろ出力について調べてみたけど、`kinship2`というRパッケージが有名らしいです。とは言っても、edgelistの方が、出力そのものはシンプルなので取り組みやすい気がしますが。しかし２倍体。。
* コミットするたびにheavywatalさんのスマホが震える感じなの？最近朝３時くらいから仕事する機会が多くて、変な時間に通知してしまう様だと申し訳ないなーと思って。

**Comment by heavywatal** [comment]
`kinship2`初めて聞きました。いかにも家系図っぽいT字のやつを描きたいならそういうのを使ったほうがいいのかもしれませんね。僕はなるべく汎用な有向グラフとかにしておくのがいいかと思ってedgelistを提案しましたけど、秋田さんが使いたいやつでいいです。edgelistの例はこのスレッドの最初の投稿で示したやつです。fromが親でtoが子供。

コミットだけでは何も鳴らないので大丈夫です。ここへの書き込みはgmailが鳴りますけど、それもまあうるさければフィルタかければ済むので気にしなくていいですよ。

**Comment by teTUNAakita** [comment]
例えば、0が父で、1が母、2と3がその子供だとすると
```
from to
0 2
0 3
1 2
1 3
```
で、以下のような出力ですね。最初はこの形式で進めたいと思います。
[tmp.pdf](https://github.com/teTUNAakita/cpp_practice/files/630233/tmp.pdf)

**Comment by teTUNAakita** [comment]
母艦でつくった鍵を.sshに入れたのに、このマシンからだとうまくいかないな。。#12は以前指摘いただいた参照渡し？問題が発生しているようです。

**Comment by heavywatal** [comment]
試しにコミットに対するコメントを使ってみたんですが 6ad105a9c3c44b719e6f5f31f80a09e9ac73558b 、これは通知鳴らないんですかね？
`size_t i=0` を使うようにしてください。(ついでに、ほかの場面で型の変換が必要になったとしても `(int)some_number` ではなく `static_cast<int>(some_number)` とするのが正しい方法です。）

`.ssh/` はパーミッションが正しく設定されてなくて動かないケースがよくあるので確認してみてください。あとは `~/.gitconfig` も必要ですけどこっちは大丈夫ですか？

参照渡しの問題って何のことですか？？？

`Population::print_family_ids()` の設計がイマイチです。せっかく `Individual` もいろいろ関数を持たせられるクラスなので、print仕事もそれを活用しましょう。たとえばこんな感じのconstメンバ関数を`Individual`クラスに定義しておけば、`Population`のほうでは順番に呼ぶだけで済みますね。

```c++
void print() const {
    std::cout << parents_ids.first  << "\t" << id << "\n"
              << parents_ids.second << "\t" << id << "\n";
}
```

`get_*()`とか`print_*()`など、変数を変更するつもりのないメンバ関数は常にconstメンバ関数にするよう意識してください。っていうか何も考えずデフォルトでconstつけるくらいの気持ちでいいです。

数が10から始まると読むときに必要な情報処理が増えるので0からにしてもらえますか？

**Comment by teTUNAakita** [comment]
> 試しにコミットに対するコメントを使ってみたんですが 6ad105a 、これは通知鳴らないんですかね？

通知は来ないようで、Gmailにも来ていなかった。型変換についてありがとうございます。

> ~/.gitconfig も必要ですけどこっちは大丈夫ですか？

はい、こちらを忘れておりました。

> 参照渡しの問題って何のことですか？？？

Population::print_adult_ids()で以下の問題が起きてないかなという類推でした。
https://github.com/teTUNAakita/cpp_practice/issues/9#issuecomment-262863339

edgelistの図も作ってみました。
[tmp.pdf](https://github.com/teTUNAakita/cpp_practice/files/633046/tmp.pdf)

**Comment by heavywatal** [comment]
Excellent! ただ`Population::get_father_id()`まで作るのはちょっとやり過ぎですかね、コードあんま短くなってないし安全性が高まるわけでもないし...。

あとはせっかく`size_t`の存在を知ったので、`int`よりも`size_t`がふさわしいと思しきところはすべて`size_t`に置き換えましょう。STLコンテナのサイズやインデックス(`[ ]`で指定するやつ)は全部そうです。自由なのは秋田さんが自分で定義するIDだけですね。

このへん直したらcloseしちゃってください。
