### ISSUE TITLE
Use random number generator

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#13]
C++11から標準ライブラリで優秀な`<random>`が提供されているのでそれを使います。

- 毎回違う結果にしたい場合、シードは`std::random_device`から取れる。
- 乱数生成エンジンは`std::mt19937`という型のオブジェクト。コンストラクタでシードを与えるか、コンストラクト後に`seed()`メンバ関数でシードを与える。
- 確率分布もオブジェクト。例えば正規分布は`std::normal_distribution`型で、平均値と標準偏差をコンストラクタに与えて初期化する。
- 確率分布オブジェクトの`operator()`に引数をしてエンジンを渡すと、`double`型の乱数が得られる。`operator()`の意味は関数オブジェクトでググれば分かると思います。

```c++
int main() {
    // seed
    std::random_device rd;
    const auto seed = rd();

    // engine
    std::mt19937 rng(seed);

    // probability density distribution
    const double mean = 0.0;
    const double sd = 1.0;
    std::normal_distribution<double> dist(mean, sd);

    // generate!
    for (size_t i=0; i<8; ++i) {
        std::cout << dist(rng) << std::endl;
    }

    return 0;
}
```

子の数をPoisson分布で決めるコードに書き変えてみましょう。エンジンオブジェクトと分布オブジェクトをどこに定義するかは結構微妙な問題です。エンジンはグローバル変数か、`Population`のメンバ変数か静的メンバ変数。分布は毎回生成でもそんなにコストかからないと思いますが、中立を仮定してシミュレーションを通して固定ならエンジンと同じとこに定義すればいいです。

**Comment by teTUNAakita** [comment]
乱数関係は全てグローバルにおいてしまいました。また、１ペアが産む場合は、必ず息子と娘をセットで産むとし、その息子-娘のペア数がポアソンに従うとしました。

**Comment by heavywatal** [comment]
Amazing!! もうかなりそれらしい家系図が描けますね。
あとは前にも言ったように`(size_t)xxx`という形の型変換は金輪際使わないでください(`std::poinsson_distribution`のテンプレート引数を`size_t`, `unsigned int`, `unsigned long`などにするのがここでの根本的な解決かと思います)。それだけ修正したらcloseして先に進みましょう。
