### ISSUE TITLE
Be aware of memory allocation of std::vector

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#14]
Cの生配列と違い、予めサイズを決めなくてもどんどん`push_back()`していけるのが`std::vector`のいいところですが、サイズを徐々に拡大していくことにコストが無いわけではありません。最終サイズが予測できる場合は`reserve()`メンバ関数で予めcapacityを確保しておくことでそのコストを減らすことができます。その理由や、`resize()`メンバ関数との違いなどについて軽く調べて、コードを修正してください。

**Comment by teTUNAakita** [comment]
* `reserve()`そのものは領域を追加で確保するので、計算時間は余計にかかるみたいですね。サイズ拡大がある量を超えたら、計算時間も短くなるのでしょうか？
* `resize()`は`reserve()`と異なり、実際に要素数を増や、という理解です。現在のコードの目的には、使い勝手があまりよくないですね。使うと、0を`MAX_ID`の分だけprintしてしまう。。

**Comment by heavywatal** [comment]
`reserve()`自体は当然コストのかかる仕事なので、使わない分まで確保したら余計に遅くなります。例えば`tmp_boy`で毎回百万も確保するのはやりすぎです。最終的な要素数が分かっている場合にその分だけ`reserve()`しておくと、そうせずに順々に`push_back()`で領域を広げていく(このときどんなコストフルな処理が発生するかは調べましたか？)よりもちょっとマシになる、というのが正しい使い方です。今回はポワソン乱数なので確実な値はわかりませんが、期待値程度かそれよりちょっと大きめくらいに確保するのが良いのではないでしょうか。

あとオブジェクトの寿命にも注意を払ってみてください。例えば`Population`のコンストラクタでメンバ変数たちの`reserve(MAX_ID)`してますが、これはコストだけかかってメリット0です。

`resize()`についてはそうですね。使い勝手の問題ではなくて明確に用途が違うんですが、だいたいそんな感じです。

まだぜんぜん速度が問題になってない段階なので、そこまでチューニングしなくていいです。軽く流す程度の課題のつもりでした。とりあえず`MAX_ID`は消して、`tmp_boy`と`tmp_girl`のほどほどな`reserve()`だけにしてみてください。

**Comment by teTUNAakita** [comment]
> reserve()しておくと、そうせずに順々にpush_back()で領域を広げていく(このときどんなコストフルな処理が発生するかは調べましたか？)よりもちょっとマシになる

push_back()で要素を追加したとき、vectorクラスが内部的に持っているメモリが足りなければ、一括していくらかのメモリが確保される（1. 新しい領域の確保・2. 古い領域から要素を新しい領域にコピー・3. 古い領域の消去）。このようなコストフルな処理を防ぐために、reserve()で実際の要素数より大き目の領域をとっておく、、といったところでしょうか。

**Comment by heavywatal** [comment]
Excellent! そんな感じです。
せっかく `elapsed_time` を作ってあるのに使わないと警告が出るので、標準出力に影響が出ない方法で書き出せるように変更してみました e4c3c96 。`./a.out >out.tsv` でファイルに流れるのは`std::cout` だけで、 `std::cerr` に流したものはコンソールに書き出されます。さらに `./a.out >/dev/null` とすればファイルIO以外の部分を計測できます。
