### ISSUE TITLE
Age structure

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#15]
齢構成はどんな感じで入れる想定でしょうか？
1. 生まれた次の年から10年間、同じ分布の乱数で繁殖し、パタッと死ぬ
1. ちゃんと齢ごとのsurvival rateとfertility rateをパラメータにして乱数振る
1. ほか

**Comment by teTUNAakita** [comment]
>  ちゃんと齢ごとのsurvival rateとfertility rateをパラメータにして乱数振る

 がもちろん最終型です。厳密には、ある程度回して安定齢分布にしたいところです。さらに、
* 子の数がある齢の個体数の線形和で決まる場合（標準的なレスリー行列を適用）、
* 子の数が非線形に決まる場合（子の数が親数によらず一定など）
の両方が考えられると思います（最終型は後者）。

**Comment by heavywatal** [comment]
さて、どういう作戦で書きましょうかね。とりあえず大きく分けて2つのやり方が思いつきます。どっちが正解かはある程度書き進めてみないと分からないので、あまり考えずに好きなほうで始めてみてください。

- Cっぽくてシンプルなのは、現在単年となっている `fathers` メンバ変数を `std::vector<std::vector<Individual>> males` みたいにして、生まれ年ごとに個体ベクタを保持するような形でしょうか。(e.g., 0年生まれの祖先たちは `males[0]` 、2016年生まれの個体たちは `males[2016]`)
- 一方、個体ごとに`unsigned int age`というメンバ変数を持たせて、`Population`ではフラットな`std::vector<Individual>`を保持することにする、というほうがオブジェクト志向らしくてカッチョイイですね。僕はたぶんこっちのほうが好きです。

あと図や表をキープしつつ議論したい場合はここじゃなくてWiki機能を使う手もあるので、よければ使ってみてください。
https://github.com/teTUNAakita/cpp_practice/wiki

**Comment by teTUNAakita** [comment]
* 個体は絶対に死なない
* 年齢に関係なくポアソンで産む

という仮定に沿って作ってみました。個体の生まれ年`unsigned int Individual::age`を出力するようにしてあります。

**Comment by heavywatal** [comment]
Excellent! それらしく動きますね！とりあえずパッと思いつく改善点だけ挙げますと

- `Individual::age` が実は年齢じゃなくて生まれ年であるという罠。生まれ年にするなら変数名を`birth_year`か何かに。`age`という名前なら全員0からスタートして毎世代`++`するような運用に。最終的にどっちが楽かは不明なのでお好きな方で始めてみて下さい。
- 現在の年`generation`は`main()`の一時変数じゃなくて`Population`のメンバ変数のほうが合理的なのではないか。
- 同様に、`parent_number`という変数が`update()`の引数や返り値として`main()`を出入りすることに違和感あり。

この調子でドンドン進みましょう。

**Comment by teTUNAakita** [comment]
`age`も`birth_year`も両方とも保持しておこうと思うのですが、`static int Individual::LATEST_ID`のように、`static int`だと良くない理由は何かありますか？

**Comment by heavywatal** [comment]
んー、完全に冗長なのでどっちかひとつにしたいです。

staticメンバ変数はクラスで1つだけ持って共有されるもので、それぞれのオブジェクトが別の値を持つ普通のメンバ変数とは全く異なります。「クラスと結びついたグローバル変数」というふうに言い換えることができるもので、あまり使うべきではありません。`LATEST_ID`も原理的には`Population`の普通のメンバ変数にするほうが正しいのですが、ちょっと手抜きして`Individual`のstaticメンバにしてる、それが分かるように大文字にしてる、という状況です。

**Comment by teTUNAakita** [comment]
ありがとうございます。
* 指摘いただいた通り訂正してみました
* ランダム交配を入れてみてから、死亡過程などを入れてみたいと思います
* `git commit`を間違えた時は、取り消してから`git push`しなきゃですね

**Comment by heavywatal** [comment]
- 何世代まわすか、という数を`update()`の引数に
- 現在何世代目か、という数を`Population`のメンバに
するのがいいんじゃないすかね。

あと`parent_number`もメンバ変数にするほどじゃないと思います。まあランダム交配とかを入れる過程で勝手に消えると思うのであまり気にしなくてもいいですが。

という変更、言うより早いのでコードを変更しました。

**Comment by teTUNAakita** [comment]
ありがとうございます。
```
for (size_t i=0; i < n; ++i) {
            ++generation;
            size_t parent_number = fathers.size();
            for (size_t i = 0; i < parent_number; ++i) {
```

の`i`かぶりは意図的ではないですね？

**Comment by heavywatal** [comment]
すいませんちょっとバタバタしててビルドすらせずコミットしました。修正しました。

**Comment by teTUNAakita** [comment]
* 個体は死なないが、ランダム交配で子孫を残す
* メスがポアソンで子を残し、その子達の父親はランダムに決まる

というモデルに拡張しました。`update()`内で
`const size_t tmp_father_id = (int)(uniform(rng) * (double)father_number);`
という禁断のキャストをしてしまいましたが、`static_cast<int>(xxx)`では動いてくれませんでした。

**Comment by heavywatal** [comment]
適切な分布関数を使いましょう。
```
std::uniform_int_distribution<size_t> uniform_int(0, father_number - 1);

std::bernoulli_distribution bernoulli(0.5);
```

http://en.cppreference.com/w/cpp/numeric/random

**Comment by teTUNAakita** [comment]
死亡過程を考えていて、５０％の確率で必ず死ぬという状況を組み込もうとしてます。`update()`関数内で、
```
size_t father_number = fathers.size();
for (size_t i = 0; i < father_number; ++i) {
        bool death = bernoulli(rng)
        if (death) {
            fathers.erase(i);
        }
}
```
のようなものを考えたのですが、配列の長さが変化していくので、いろいろとトリックをかまさなければいけないようです。死亡過程を扱うのに、'erase()'以外の候補はありますか？それとも'erase()'で頑張った方が良い感じでしょうか？

**Comment by heavywatal** [comment]
前みたいに`next_fathers`のような一時変数を作って、出産と`if (survive)`で`next_fathers.push_back()`していって、`update()`の最後で`fathers.swap()`する、とか。

**Comment by teTUNAakita** [comment]
* ありがとうございます、指摘の通りに組み込みました
* 死亡過程が入る場合、親子関係を追うのが複雑になったため、暫定的に重複を許す感じで出力させ、
`run.sh`の中で`awk '!x[$0]++' out.tsv > out_dup_removed.tsv`とし、重複を除去してから図示するようにしました

**Comment by heavywatal** [comment]
死亡とランダム交配はいい感じになってきましたね。

別のアイディアとして、生まれた瞬間に書き出すことにしちゃえば書きそびれも重複も起こらなくていいんじゃないかと思います。

ほかに些細なことをいくつか
- `update()`内でsurvivalとreproductionをコメントで区切ってますが、それはもうそろそろ関数を2つに分けたいサインです。
- survivalの評価を後にもってくれば `generation==0` を毎回評価しなくて済むのでは。

ってことで少し修正したいと思います。

**Comment by heavywatal** [comment]
あコミットコメントに #15 つけるの忘れました。

**Comment by teTUNAakita** [comment]
* 早速ありがとうございます
    * 一大プロジェクトにこのシミュレーション結果を使うことになりそう?なので、締め切りがさらに早まりました...　年内になんとか形にできたらと思います
    * というわけで、謝辞や共著で、heavywatalさんが複数回出てくることになりそうですが（もちろん事前にお知らせします）、このトレーニング以外は負担をかけないようにしますので、今後もお付き合いいただけたらと思います
* 次は、年齢依存の死亡＆再生産を加えたいと思います

**Comment by heavywatal** [comment]
了解です。ここも長くなってきたので、年齢依存の死亡＆再生産は別スレッドにしようと思います。
#16 のファイル分割に取り組んでみてください。
