### ISSUE TITLE
Age-dependent survival and fertility rate

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#17]
型はおそらくどちらも `std::vector<double>` でいいと思うんですが、どこで定義するのがいいでしょうね。`Individual`クラスのstaticメンバ変数か、`Population`クラスのメンバ変数か。

**Comment by teTUNAakita** [comment]
* survival rateだけ組み込んでみました
* ファイルを分割してしまうと、現状の`makefile`だと`.hpp`だけ更新した時に、`make`でコンパイルし直してくれないのですね
* 後々のオプションの話ですが、TUNAは、１シーズンあたりたくさんのmaleと交配があるようで、繁殖のモデリングのオプションが結構複雑になりそうです

**Comment by teTUNAakita** [comment]
'const auto tmp_age = fathers[i].get_age(generation);'のconst autoの使い方が、ググってもよくわからないです。unsigned intではダメですか？

**Comment by heavywatal** [comment]
C++11以降で利用可能な型推論という機能です。関数の返り値からコンパイラが勝手に判断してくれるので、そういう場面では `auto` で済むようになりました。記述が簡潔になるうえに、関数側の定義を変更しても自動的に反映されるメリットがあります。その部分を読むときに型が分かりにくくなるデメリットもあるので場合によっては避けますが、今回は `age`という変数名からして自明であると判断しました。この場合はそこに `const` を付けてるので `const unsigned int` と同じです。慣れなくて分かりにくかったら明示的に書いてもいいですよ。

ついでにC++11について言うと、"range-based for" や `emplace_back()` というのも導入したいのですが、それについては参照とコピーについてもう少し学んでから説明しようと思います。

**Comment by teTUNAakita** [comment]
* `auto`についてよくわかりました
* 複数オスとの交配をセットで、age-dependent fertilityを組み込みました
* survivalがオスとメスで同じコードを繰り返しているような気がするので、別の関数にした方が良いでしょうか？その場合は、`Population`クラス内のメンバ関数として扱ってい良いのですよね？

**Comment by heavywatal** [comment]
Amazing!! メスは `reproduction_proportion` でガッチリ制限されてる一方、オスは年齢に関係なくランダムに選ばれてるような感じですけど、これはbiologicalにオッケーですか？

survivalの重複を関数にしたくなったその気持ち、素晴らしいです。やりましょう。ただ僕としては `Individual` クラスに `bool die(const unsigned int generation) const { ... }` みたいなものを持たせて、 `Population` から `for` でそれを評価するっていうほうがクラスの利点を活かしていてしっくりきます。そうすると自動的に survival rate は `Individual` クラスのstaticメンバで定義することになります。

**Comment by teTUNAakita** [comment]
> オスは年齢に関係なくランダムに選ばれてるような感じですけど、これはbiologicalにオッケーですか？

そうなのです、オスの選択は繁殖の強さで重み付けするのが正解です。

* `bool die()`の実装もやってみたいと思います。
* 明日からインドですよね？課題を大量にばら撒いていただけると、年末にゴリゴリできる気がします。

**Comment by teTUNAakita** [comment]
* `Individual::die()`を使うことで、survival関数を簡略化しました。
* reproduction関数もクラス`Individual`で管理した方が良い箇所があるでしょうか？
* オスの選ばれ方の重み付けは、Cっぽく汚く書く（累積密度関数と乱数から`while`文をループして探索）のはできるのですが、何かスマートな方法はあるのでしょうか？

**Comment by heavywatal** [comment]
`i` は個体にとって何の関係もないので引数に入れるべきではないです。あと `bernoulli_survival(rng)` の返り値がせっかく `bool` なので `if` を挟まずに `return !bernoulli_survival(rng);` とかしたほうがいいです。あと自分で提案しておいてなんですが、死ななければ `push_back()` ということは `die()` より `survive()` のほうがストレートですね。デバッグコードの入れ方については別スレッドで書きます。とりあえずそれでここはクローズしますか。

**Comment by heavywatal** [comment]
あ、ちなみにオスの繁殖力に関しては、僕も普通のルーレット選択みたいなのしか思いつかないです。
