### ISSUE TITLE
Use NDEBUG macro for debug print

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#19]
こんな感じのものを上の方で定義しておいて
```c++
#ifndef NDEBUG
#  define DCERR(...) std::cerr << "\033[1;30m" << __VA_ARGS__ << "\033[0m"
#else
#  define DCERR(...)
#endif // NDEBUG
```

使いたいところでこう書いておきます。
```c++
DCERR("I'm alive!" << std::endl);
```

`"\033[1;30m"` という部分は色を変えるためのエスケープシーケンスなので、好みによって変えたり消したりしてください。普通にビルドすると `std::cerr` を通して表示されますが、ビルド時に `-DNDEBUG` というオプションを付けるとプリプロセッサによってコードそのものが消されます。ピュアなC++機能ではなくマクロなのであまり好きではないですが、最終コードにおけるコストがゼロなのが魅力です。

**Comment by teTUNAakita** [comment]
"NDEBUG color macro"でググってもよくわからなかったのですが、色を変えるためにはどこをどういじれば良いのかな？

**Comment by heavywatal** [comment]
`NDEBUG`はC/C++においてメジャーな概念ですが、出力の色を変えるのはそうしたマクロやC/C++とは全く別の問題です。ググるなら「エスケープシーケンス 色」とかですかね。シェルのプロンプトの色を変えるときとかによく使われます。

あとは `NDEBUG` つきでビルドするためのターゲットを以下のような感じで `Makefile` に追加して、`make clean && make release && ./a.out` してみて、オッケーだったらクローズしてください。

```
release:
	$(MAKE) CPPFLAGS=-DNDEBUG all
```
