### ISSUE TITLE
Use `emplace_back()` instead of `push_back()` if possible

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#22]
そこそこどうでもいい部類です。たとえば `std::vector<Individual>` に出来上がった `Individual` を `push_back()` するとコピーなりムーブなりのコストがかかるのですが、挿入と同時に `vector` 側でいい感じにコンストラクタを呼んでもらえる関数があります。それが `emplace_back()` で、これには `Individual` そのものではなく `Individual` のコンストラクタに渡すべき材料を渡します。今のコードだと、子供を作るとこで使えますね。

**Comment by heavywatal** [comment]
使い方を理解せずに間違ったコードを書いています。ちゃんと調べて正しいコードにするか、元のコードに戻してください。

**Comment by teTUNAakita** [comment]
お正月に新しいコーディングを加えて、「初期個体数10,000,000（0歳）で、毎年10,000,000個体が加入する（だれが親になるかは、成熟率で重み付けして決まる）」というコードを書いて走らせたのですが、重すぎて時間がかかりすぎる状況です。効率的なコーディングが要請されるようなので、他にも何かあったらご教示お願いします。

**Comment by heavywatal** [comment]
既にコンストラクト済みのオブジェクトを入れるときは `emplace_back()` ではなく `push_back()` を使います。

10M個体となると処理速度だけでなくメモリも厳しそうですね。気をつけて見ていきましょう。とりあえず必要な要素はもうモデルに組み込み終わって、あとは高速化するだけって感じですか？

**Comment by teTUNAakita** [comment]
`emplace_back()`の使い方OKです。理解の判断材料を動くか否かで判断していると、文法を理解する忍耐力を涵養するのが難しいですね...

メールで送った通りですが、コーディングを加えたものをある程度修正したら、commitしてよいでしょうか？また、このような議論はissuesでやるべきでしょうか？

**Comment by heavywatal** [comment]
すいません添付ファイルまだ見てないです。議論はメールでもissueでもいいんですが、ソースコードはほどよい区切りでどんどんcommitしちゃってください。そのためのgitなので。
