### ISSUE TITLE
Prefer "range-based for loop"

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#23]
```c++
// C/C++ index
for (size_t i=0; i<v.size(); ++i) {
    std::cout << v[i].get_id() << std::endl;
}

// C++11 range-based for
for (const auto& x: v) {
    std::cout << x.get_id() << std::endl;
}
```

型の受け取り方は関数の引数と似たような感じです。変えるつもりがなければ `const` 、コピーを避けたければ参照 `&` にします。

`Population::reproduction()` のループのようにコンテナそのものの長さが変わるようなときは使えないので注意してください。

C++11でrange-based forが登場してからイテレータの出番は減りましたが、それでもSTL `<algorithm>` を利用する場面とかで使う可能性もあるので覚えておいて損はありません。

```c++
// C++ STL iterator
for (auto it=v.cbegin(); it!=v.cend(); ++it) {
    std::cout << it->get_id() << std::endl;
}
```

**Comment by teTUNAakita** [comment]
コンテナのサイズが0になった場合に、致命的なエラーがたくさん出るようなので、現時点では搭載を見送っているところです。ループ数がコンテナのサイズに相当する場合、それらのサイズはすべて0になる可能性があるようなので。。

**Comment by heavywatal** [comment]
いずれのループ形式でも、コンテナサイズ0のせいでエラーが起こることは絶対にありません。おそらく別の問題だと思います。例えば、オスが0匹になったあと父親選びの `uniform_int` が 0 を吐き出し、存在しない0番目の父親にアクセスすることになる、とかはありがちですね。

**Comment by teTUNAakita** [comment]
> `Population::reproduction()`のループのようにコンテナそのものの長さが変わるようなときは使えない

`reproduction()`にある`for (const auto& x : mothers) {}`では使っても問題ないようですね。
range-based forを使うことで、不要なコピーを避けることができるということですかね。

**Comment by heavywatal** [comment]
Amazing!
でも普通の`i`のループと比べたrange-based forのメリットはコピー回避ではないです。コンテナを最初から最後まで舐めるのが明確なこと、簡潔に書けること、`const` 指定できること、ですね。
