### ISSUE TITLE
Pursuit "fast computation"

### ISSUE THREAD

**Issue by teTUNAakita** [teTUNAakita/cpp_practice#24]
加入個体数が10Mというオーダーでどのような演算高速化の道がありますでしょうか？

**Comment by heavywatal** [comment]
目についた点についていくつか変更しました。とりあえず他に思いついたのは以下の点です。

- `Individual` クラスのメンバ変数を極力軽くしたい
    - `std::pair` を解消して個別の `int` として持たせたほうが僅かに軽い
    - 静的メンバ変数はオブジェクトごとにではなくクラスに1つだけ実体化されるので大丈夫
- `recruitment()` に無駄が多い
    - `std::accumulate()` によるチェックの意義？
    - 同じ `cumsum()` を何度も計算してる

**Comment by teTUNAakita** [comment]
時間を使ってチェックいただき申し訳ないです。次回からはこまめにgit commitするようにします。また、samplingアルゴリズムの追加もありがとうございました。`sample_set(), sample_fisher(), sample_knuth()`の理解も必須ですよね...
 
> `std::accumulate()` によるチェックの意義？

成熟している個体が少なくとも集団に１個体以上いることをチェックしているものです。

> 同じ `cumsum()` を何度も計算してる

ルーレット選択（とcumsum）は、コピペで拾ってきた野良アルゴリズムなので、ちゃんと直します。

**Comment by heavywatal** [comment]
1個体以上いることをチェックしたいだけなら既に定義してある `check_size()` を使ったほうが圧倒的に速いですね。それはまあいいとして、そもそも「チェックしてダメだったら(この場合0個体になっちゃったら)どうしたいのか？」というのが僕の疑問でした。expensiveなチェックでエラーを回避できたとして、そのまんま何世代も走り抜ける意味は無いですよね？突き詰めて言えば、最終的にどういう方法でこのプログラムを回したいか、という疑問になります。基本的には絶滅しないパラメータ範囲でのtreeづくりが中心になるなら、チェックなしでエラー終了させちゃうのも手です(ただしどういうエラーで終了したかくらいは分かるようにしたほうが良いですが)。絶滅しちゃうかも知れないパラメータも含めて探索的に回すつもりであれば `throw`, `try`, `catch` を用いた例外処理を学んだほうがいいかもしれません。

**Comment by teTUNAakita** [comment]
丁寧な説明ありがとうございます。ここでチェックしたいのは、「成熟している」個体が１個体以上いるかどうかなので、集団の絶滅とはちょっと異なる点を見てました。0-3歳までは成熟しないので、4歳以上が集団中に１個体もいない場合は加入がない、というのを再現したかったのでした。説明不足で申し訳ないです。

**Comment by heavywatal** [comment]
了解です。そしたら1番速いのはcumsumを1度だけ計算して末尾を参照するとかですかねー
