### ISSUE TITLE
Initialize class object in constructor

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#4]
- コンストラクタで引数(この場合ひとつの`int`)を受け取れるようにして、その値で`id`を初期化する。
- 変える予定のない変数や引数はすべて`const`として宣言する。
- 数行程度の小さくて単純な関数は、宣言と定義を分けずにクラス定義の中に直接書いちゃう。

**Comment by heavywatal** [comment]
`id`を`const`メンバ変数に書き変えました。`git fetch && git merge`して、ビルドしてみてください。おそらくエラーが出ると思います。`const`メンバーを初期化する方法を見つけてください！

**Comment by teTUNAakita** [comment]
commitで間違えて#3をつけちゃったけど、とりあえずできました。

**Comment by heavywatal** [comment]
Excellent!! 初期化以外の勝手なとこで変更しようとするとコンパイル時点でエラーになる、という形で書いておくと、バグを未然に防ぐ上でかなり頼もしいんですよねー。
solved in caf8bd179d59f7f49d49cacf07dd798f30525ce3
