### ISSUE TITLE
Asexual proliferation

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#5]
- 祖先情報保持のため `std::vector<int>` 型の新しいメンバ変数を持たせる
- 新しい`Ind`オブジェクトを生み出すメンバ関数を書き、`main()`内で親に実行させて子を生成する
- このとき子のコンストラクタで、親の`id`を上記のvectorに`push_back()`し、新しい`id`を割り振る

**Comment by teTUNAakita** [comment]
>新しいIndオブジェクトを生み出すメンバ関数を書き
これは、class Indの中で宣言するの？

**Comment by heavywatal** [comment]
そうですね、メンバ関数というからには、普通のグローバルな関数ではなく、`class Ind`のメンバ関数として書いてほしいという意味です。

**Comment by teTUNAakita** [comment]
ヒントプリーズ

**Comment by teTUNAakita** [comment]
"子のコンストラクト"の意味があんましわからんかった。

**Comment by heavywatal** [comment]
`int`を返す関数は`int func1() {...}`と書きますよね。`Ind`を返す関数は`Ind func2() {...}` のように書きます。

現状のコンストラクタには`int`を受け取って`id`を初期化する機能しかないので、親の情報を受け取って祖先情報vectorを初期化できるコンストラクタを書く必要があります。

あと本筋ではないですが、メンバ変数の名前に`v`とかは最悪なので、意味のある名前を付けてください。これもコーディングの重要な要素です。できれば`Ind`のような省略もしないほうがいいです。

**Comment by heavywatal** [comment]
最終的には、`main()`関数内でこんな感じで子供ができるようなイメージです。

```c++
Individual parent(3);
Individual child = parent.copy();
std::cout << child.get_id() << std::endl;
// 4
std::cout << child.get_ancestor_ids()[0] << std::endl;
// 3
```

**Comment by teTUNAakita** [comment]
std::vector<int>の返し方がわからんかった（セグフォが出る）。ハッシュタグを入れてcommitしないと、ここには反映されないのね。

**Comment by heavywatal** [comment]
子の`ids_vector`が空っぽなのに存在しない`[0]`番地を参照してますね。`copy()`の中で親の`ids_vector`に`push_back()`しちゃってますよ。

**Comment by heavywatal** [comment]
Well done! 改良版を b44ce261794f4242f7f1caa6aa1434f57432cabb にコミットしたのでdiffを見てみてください。
オブジェクトの外からメンバ変数を変更するのは危険なので、`child.ind_vector.push_back(id)`のようなことは基本的に避けます。メンバ変数を`private`にしてるはそのためで、クラスの外の関数から参照しようとするとコンパイルエラーにしてくれるのですが、今回は`Individual`クラスのメンバ関数での出来事だったので通ってしまいましたね。メンバ変数をいじるときはそのオブジェクト本人のメンバ関数を通して行う、という習慣をつけましょう。
