### ISSUE TITLE
Setup github account

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#6]
- パスワード無しのSSH公開鍵を生成して、マシンとGithubに登録。
- `~/.gitconfig` を設定して、どのマシンからでも同じアカウントとしてアクセスできるように。

**Comment by teTUNAakita** [comment]
鍵は作ってあるのだけど、~/.ssh/configで設定すべき？それとも~/.gitconfig？

**Comment by heavywatal** [comment]
`~/.ssh/config`はGitHub関連設定には使えないと思います。
ちなみに僕の`.gitconfig`はこんな感じになってます: https://github.com/heavywatal/dotfiles/blob/master/.gitconfig

**Comment by teTUNAakita** [comment]
Thanx, I did #6.

**Comment by heavywatal** [comment]
では、なにか適当な変更をして、`Close #6`というコメントでcommit、pushしてみてください。パスワードなしでpushできて、この履歴に @teTUNAakita として登場すればクリアです: https://github.com/teTUNAakita/cpp_practice/commits/master
