### ISSUE TITLE
Use static member variable for ID assignment

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#7]
- `Individual`クラスに`int`型の静的メンバ変数を作る(名前は例えば全部大文字で`LATEST_ID`とか)。
- 新しい個体を作るとき`LATEST_ID`の値を使って`id`をセットし、`LATEST_ID`を1増やす。
- 結果的に、コンストラクタにIDを渡す必要がなくなり、みんなが異なる値を持つことになる。

**Comment by teTUNAakita** [comment]
"結果的に、コンストラクタにIDを渡す必要がなくなり"
とういうことは、コンストラクタの引数が１つになり、親のid初期化のコンストラクタとかぶってしまうため、オーバーロードできなくなる？？

**Comment by heavywatal** [comment]
親のID初期化に、引数を取るコンストラクタが必要でしょうか？

**Comment by teTUNAakita** [comment]
int Individual::LATEST_ID = 0;
でオッケー？

**Comment by heavywatal** [comment]
質問が曖昧で答えようがありません。

**Comment by teTUNAakita** [comment]
おけ、とりあえず完成させます。

**Comment by teTUNAakita** [comment]
どこでpush_backさせてよいかわかんなかった。

**Comment by heavywatal** [comment]
`maybe wrong`のところ、間違ってます。`push_back()`を呼ぶ場所はここであってますが、親のIDがいつも"最新-1"とは限らないですからね。
あと`LATEST_ID`をどこでインクリメントするべきかをもっとよく考えましょう。`copy()`関数内で`++`するのは間違いです。新しいオブジェクトができるときはいつでも確実に`++`したいのです。

オブジェクト志向思考に慣れてないとちょっと難しいかもしれないので、もっかい提出してもらったら解答だします。

**Comment by heavywatal** [comment]
ちょっとあまりにもひどい間違いだったので解答だすのやめます。`get_id()`で数字を参照するごとに静的変数がインクリメントされて良いわけないですよね。ひとつずつ質問していきます。

新しいオブジェクトを作るためのメンバ関数、すなわち、新しいオブジェクトが作られるときに必ず呼ばれるメンバ関数のことをC++ではなんと呼ぶでしょうか？

**Comment by teTUNAakita** [comment]
コンストラクタ？初期化なような気がするけど。。

**Comment by heavywatal** [comment]
ピンポーン！コンストラクタです。
`LATEST_ID`を参照する必要があるのはコンストラクタだけですし、インクリメント処理もそこで行うべきですよね。このヒントで行けるでしょうか。

**Comment by teTUNAakita** [comment]
それに近いコードも試したんだけど、printの結果は間違っているんだよね。とりあえず提出します。

**Comment by heavywatal** [comment]
結果じゃなくて論理を重視してください！

**Comment by heavywatal** [comment]
さっきよりも良くなりました。1行ごとにコメント入れてみたので`git pull`してください。

**Comment by teTUNAakita** [comment]
ありがとうございます。idを変更するには、コンストラクタで初期化するしかないよね？でも新しい値で初期化すると、前の値の情報が消えてしまうので、push_backで祖先情報を格納できないよね？？
Individual copy(){
        return Individual(LATEST_ID);       // wrong
}
は何か追加が必要？？

**Comment by heavywatal** [comment]
`main()`の頭から順を追って考えましょう。
1. まず引数なしのコンストラクタで`parent`が作られ、`LATEST_ID`を参照して`parent.id`に0が代入されます。
2. 次に`parent.copy()`が呼ばれます。
3. その中で、整数を一つ取るほうのコンストラクタに`LATEST_ID`を渡してしまっています。ここで渡すべきなのは、`Individual`クラスの最新IDではなく、`copy()`を呼び出した親個体の`id`ですね。
4. コンストラクタの引数の名前(`num`)が曖昧で良くないです。ここで受け取りたいのは`ids_vector`に入れるための親のIDなので、`parent_id`とかにしておきましょう。
5. 次に0のままの`LATEST_ID`で`child.id`が初期化されてしまいます。そのまえに`LATEST_ID`を1にしておきたいところです。
6. `ids_vector`には0のままの`LATEST_ID`を`push_back()`する結果、たまたま正解の値ですが、論理的には全く間違ってます。引数で受け取った`parent_id`(元`num`)を入れましょう。
7.  とすると、`LATEST_ID`はもっと早い段階で`++`しちゃっても大丈夫ですね。僕なら2つ両方のコンストラクタの初期化のところで`: id(LATEST_ID++) {`というふうにします。それなら確実に新しいオブジェクトが作られる度に最新のIDが更新されます。

**Comment by teTUNAakita** [comment]
Individual(const int parent_id) : id(LATEST_ID++) {
        ids_vector.push_back(parent_id);
        std::cout << "id=" << id << std::endl;
        std::cout << "parent_id=" << parent_id << std::endl;
        std::cout << "LATEST_ID=" << LATEST_ID << std::endl;
    };
はparent_idをidで初期化したのちにLATEST_IDをインクリメントするということですね。丁寧に解説ありがとうございます。でもここのidが1になるのはなんでかな？？

**Comment by heavywatal** [comment]
そのコンストラクタの表記だけからは「`parent_id`を`id`で初期化」するかどうかはわかりません。今回はたまたま「親が`Individual(id)`という形そのコンストラクタを呼ぶので、子のオブジェクトから見たそのコンストラクタの`parent_id`には親の`id`の値が格納されている」というだけです。

ちょっと質問の意図がわかりません。「ここの`id`が1」というのは、オブジェクトでいうと誰の`id`の話ですか？`child.id`のことだとすれば、`parent.id`を0で初期化したあと`LATEST_ID`の値は1に進んでいて、その値で`child.id`を初期化するからです。`++i`と`i++`の挙動が違うことはご存知ですよね？

**Comment by heavywatal** [comment]
腑に落ちない点があったらジャンジャン訊いてください。ここまでオーケーなら、このissueをcloseして #6 に取り組んでください。

**Comment by teTUNAakita** [comment]
最初の親を定義するときのコンストラクタ
Individual() : id(LATEST_ID++) {}
について、
・parent.idをLATEST_ID++で初期化
しているのではなく、
・parent.idをLATEST_IDで初期化したのちに、LATEST_IDをインクリメント
しているということかな。この書き方は知らなかった（++LATEST_IDの挙動だと勘違いしてた）。

-------
Individual copy(){ return Individual(id); }
Individual(const int parent_id) : id(LATEST_ID++) { ids_vector.push_back(parent_id); }
-------
は、
１：parent.idでparent_idを初期化し、child.idをLATET_IDで初期化したあと、インクリメント
が正解なのかな？でも全然そういう風には読めなくて、
２：return Individual(id)のid(=parent.id?)でparent_idが初期される。return Individual(id)のidとLATEST_IDは同じ値のはず？？下記の例(3.1_Candlemass)のように、
------
public:
 Ind(const int num) : id(num) // id(num)はおまじない
int main{Ind mats(666);}
------
まだ１０％くらいしかわかってない。。

**Comment by heavywatal** [comment]
厳しいかもしれませんが、大事なとこなのでじっくり行きましょう。

どのオブジェクトとしてメンバ関数を実行したか、という意識がまだ希薄なのかもしれませんね。今誰の関数の中なのかを常に意識しながら`main()`から辿ってみるといいと思います。あと、`child`とか`other_guy`でも`copy()`して孫や別の子を作り、全オブジェクトで`get_id()`からプリントしてみてください。

あと、ここをキレイに書くにはMarkdown記法(Github Flavored Markdown)を調べてみるといいですよ。

**Comment by teTUNAakita** [comment]
色々とお手数かけました。ほぼ１００％理解した。しばらくわからなかった点は、
1. `return Individual(id)`が、子オブジェクト生成に対応することを理解していなかった。
2. 引数ありのコンストラクタで、`:id(LATEST_ID)`のプロセスと引数そのものは無関係（普段関数とか使わないから混乱した）。
でした。

**Comment by heavywatal** [comment]
Well done!
