### ISSUE TITLE
Create Makefile

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#8]
こんな感じの`Makefile`を作って、`make`コマンドだけでコンパイルされるようにしてください。最新のソースファイルの名前を`main.cpp`とすることにしましょう。

```make
CXX = clang++
CXXFLAGS = -Wall -Wextra -O3 -std=c++14
CPPFLAGS = -I/usr/local/include -I${HOME}/local/include

.DEFAULT_GOAL := all
.PHONY: all clean

all: a.out
        @:

a.out: main.cpp
        $(CXX) $(CPPFLAGS) $(CXXFLAGS) $^ -o $@

clean:
        $(RM) a.out
```

スペース8個のところはTABひとつに置き換えてください。

**Comment by teTUNAakita** [comment]
#9で、
> makeでビルド可能になったmain.cppをadd
とあったけど、makeでビルドすることは、main.cppファイルの中身によらずに実行可能なので、もうcloseしても良いのかな？つまり、makefileの中身に応じて、main.cppにおまじないを追加したりする必要はないのだよね？

**Comment by heavywatal** [comment]
だいじょぶでーす

**Comment by heavywatal** [comment]
あ、ファイルをaddしたcommitでcloseしてくださいね。

**Comment by heavywatal** [comment]
あすでに f4427789482022581aeb09e05cae96d38514a651 でaddされてましたね。クローズしまーす
