### ISSUE TITLE
Make diploid class

### ISSUE THREAD

**Issue by heavywatal** [teTUNAakita/cpp_practice#9]
- 両親のIDを受け取るコンストラクタを書く
- それらを格納するメンバ変数は`std::vector<int>`か、`std::pair<int,int>`か、2つの`int`か、お好みで。
- `get_id()`など、メンバ変数を変更しないメンバ関数を「constメンバ関数」にする。
- `main()`のなかで父、母、子を作り、それぞれのIDと両親IDをプリントして確認する。

**Comment by teTUNAakita** [comment]
* main.cppと統一すると、今後の課題の名前がかぶってしまうね。課題毎にフォルダを作成して、その中に入れたほうが良いのかな？
*Individual child = mother.copy(father_id)としてchildを生成したけど、父母を非対称ではなく対称的に扱いたい場合は、どのように実装したら良いのだろうか？

**Comment by heavywatal** [comment]
とりあえず`make`でビルド可能になった`main.cpp`をaddして #8 をcloseしてください。せっかくgit使ってるので、過去のソースコードを別名で保存する癖は捨てましょう。`main.cpp`ひとつあれば十分です。

無理にメンバ関数を使わなくてもいいですよ。両親を対象に扱う関数を作りたい場合は`Individual`クラスの「静的メンバ関数」を作るという手もありますが、最低限必要なのは`int`を2つとるコンストラクタだけです。それさえあれば、例えばこのように子作りできます。
```c++
Individual mother;  // default constructor
Individual father;  // default constructor
Individual child(mother.get_id(), father.get_id());  // constructor with two ints
```

**Comment by heavywatal** [comment]
ちょびっとだけ手を加えたので`git pull`してください。`using namespace std;`は悪の呪文なので永久に封印しましょう。`parents_ids`もconstメンバにして、コンストラクタの実装部じゃなくて初期化子で固めちゃってください。それができたらここはcloseということで。

**Comment by teTUNAakita** [comment]
> parents_idsもconstメンバにして、コンストラクタの実装部じゃなくて初期化子で固めちゃってください。
```
private:
 std::pair<const int, const int> parents_ids;
```
と宣言するまではわかるけど、そのあとどのように初期化子を書けば良いのかな？
例えば、idの初期化のように、
`int Individual::parents_ids=() : first(0), second(0);`
のようなコンストラクタを使うのかな？ヒントプリーズ。

**Comment by heavywatal** [comment]
それだと`first`と`second`の書き変えが可能なままですね。正しくは`const std::pair<int, int> parents_ids`です。

初期化子というのは、別の言い方をすると「メンバ変数のコンストラクタを呼ぶ場所」です。たとえば既存の `Individual() : id(LATEST_ID++) {}` という部分も、`int`をひとつとる`int`のコンストラクタを呼び出して`id`を初期化していると捉えるわけです。下の例を見てみてください。
```c++
int x = 2; // コンストラクタを呼び出してないように見える初期化
int y(3);  // コンストラクタを呼び出してるっぽい初期化
x * y      // 6
```
どっちで書いてもコンパイル後のコードは同じで、前者のほうが読みやすいのでそうすべきですが、`class`を学んだあとだと後者のほうが一貫性があってしっくりくるというか、そういう書き方もありだというのは知っておいて損はないですね。

つまり言いたいのは、`std::pair`に限らず、C++において何らかのオブジェクトを初期化したいと思ったときはとにかくまずコンストラクタを調べるということです。[`std::pair`のコンストラクタ](http://www.cplusplus.com/reference/utility/pair/pair/)を見ると、初期化の方法がいくつかあることがわかりますね。そのなかに`first`と`second`を与える方法もあります。

**Comment by teTUNAakita** [comment]
初期化の説明ありがとう、両親のIDを受け取るコンストラクタの中に、parents_idsの初期化コンストラクタを入れてみました（この表現で良いのかな？）。
`const std::pair<int, int> parents_ids;`について、まだよくわからないのが、
1. privateで宣言しつつ、publicの中にあるメンバ関数でも初期化して、と記述が冗長な気がする。
2. `main()`から`parents_ids'に格納された父IDに`child.get_farther_ids()`でアクセスすると、異なる値(=0)を吐き出す。
という状況です。。

**Comment by heavywatal** [comment]
あーコンストラクタの `{ 実装部 }` に同名の新しい変数を作っ(てただちに破棄し)ちゃってますね。「初期化子」でググってください。初期化子を書ける場所は、引数の後のコロンから中括弧の始まりまで、つまり`id(LATEST_ID++)`がいるとこだけです。`parents_ids`もそこでしか初期化できません。今のところ、コンストラクタの `{ 中括弧のなか }` に書くべきことはひとつもないです。

**Comment by heavywatal** [comment]
Excellent! 初期化子以外の場所で値を動かせない、ガチガチに安全なクラスができあがりましたね。 `get_parents_ids()` は今のところコピーを返す書き方になっているため返り値にconstが付いてるのはあんまり意味なくて、ホントはconst参照返しにするのがベストですが、それについてはまたの機会に説明します。
